---
title: "THE TITLE"
shorttitle: "THE SHORT TITLE"
author:
  - name: Robert Esposito
    corresponding: true
    email: rme70@rutgers.edu
    affiliations:
      name: "Rutgers University"
      department: Department of Spanish and Portuguese
      address: 15 Seminary Pl.
      city: New Brunswick
      region: NJ
      country: USA
      postal-code: 08901
author-note:
  # Disclosures condensed to one paragraph, but you can start a field with two line breaks to break them up: \n\nNew Paragraph
  disclosures:
    # Example: This study was registered at X (Identifier Y).
    study-registration: ~
    # Acknowledge and cite data/materials to be shared.
    data-sharing: ~
    # Example: This article is based on data published in [Reference].
    # Example: This article is based on the dissertation completed by [citation].  
    related-report: ~
    # Example: [Author name] has been a paid consultant for Corporation X, which funded this study.
    conflict-of-interest: The authors have no conflicts of interest to disclose.
    # Example: This study was supported by Grant [Grant Number] from [Funding Source].
    financial-support: ~
    # Example: The authors are grateful to [Person] for [Reason].
    gratitude: ~
    # Example. Because the authors are equal contributors, order of authorship was determined by a fair coin toss.
    authorship-agreements: ~
number-sections: true
abstract: "The abstract goes here."
keywords: [keywords, go, here]
floatsintext: true
bibliography: "./lit/cog_interp_final.bib"
format:
  apaquarto-docx: default
  apaquarto-html: default
  apaquarto-pdf:
    documentmode: man
---

THE INTRODUCTION GOES HERE.

## Using Intonation to Predict Sentence Type in Spanish

When listening to speech, humans are exposed to an acoustic signal that is seldom encoded in writing: fundamental frequency (F0). F0, modulated by how fast the vocal folds vibrate, is interpreted in human languages such as English and Spanish as discrete pitch targets (high or low) and organized at the utterance-level to provide syntactic, pragmatic, and paralinguistic information. Broadly speaking, intonation can be used to signal speech act marking, information status, belief status, and politeness, among many other communicative functions [@prieto2015intonational; @best2019diversity; @arvaniti2020autosegmental; @cruttenden1997intonation; @cutler1997prosody; @dahan2015prosody; @gussenhoven2004phonology; @ladd2008intonational]. Relevant to this study, intonation may also encode sentence modality: @hirst1998survey found that approximately 70% of a sample of nearly 250 languages used the final pitch movement to signal interrogativity. Spanish is an example of such a language, in which an utterance e.g., 'Mariano habla del tiempo' *Mariano talks about the weather* may variably be a statement or question, differentiated only by intonation. Importantly, @hirst1998survey categorized languages using only the final F0 movement, and this has been the traditional analysis for Spanish as well [@tomas1974manual; @hualde2008intonation].

It seems unlikely that Spanish listeners should wait until the very end of an utterance to determine sentence modality. Humans constantly make predictions [@bar2007proactive; @lee2003hierarchical], and it follows that we also anticipate linguistic information [@van2012prediction]. Such a hypothesis has been supported across linguistic domains [e.g., @altmann1999incremental]. Prosody and intonation have traditionally received little attention [@cutler1997prosody], but the extant research has demonstrated that listeners integrate intonational information as sentence processing unfolds to make predictions of upcoming content [@esteve2020empathy; @grodner2010some; @kamide2003time; @crocker2010computational; @levy2008expectation]. Based on this evidence, it would be expected that L1 Spanish speakers do not wait until the final F0 movement to determine sentence modality, but instead integrate early intonational information to make predictions.

However, not all intonational cues are weighted equally for a listener. @roettger2019evidential attempts to address this issue by introducing a computational model that proposes that the predictive value of an intonational cue is dependent on the prior reliability of the cue-to-function mapping and the likelihood of the mapping given the listener's most recent experiences. In a later series of mouse-tracking studies, @roettger2021positional found that L1 German speakers did not use available prenuclear pitch accents for anticipatory behavior when determining ambiguous referents. On the other hand, some, but not all, L1 American English participants recruited the early intonational cues to anticipatorily disambiguate the referent. This research puts doubt on the claim that L1 Spanish speakers recruit early intonational cues during on-line processing to determine sentence modality, as opposed to waiting for the final F0 movement.

Traditionally, only the last F0 movement is pointed to as the meaningful difference between the two sentence types [@tomas1974manual; @hualde2008intonation], but other leftward intonational cues have been identified [@sensui1995perception; @sensui2003pilot; @face2004intonation; @face2005f0]. @face2005f0['s] off-line gating experiment unequivocally rejected the final F0 movement as the only cue for sentence modality: L1 Spain Spanish speakers can accurately determine sentence modality by the scaling (i.e., height) of the first F0 peak and the presence or absence of a medial pitch accent. In a follow-up off-line gating experiment [@face2007role], he found that these early cues hold dramatically less weight than the final F0 movement, which seems to "override" the sentence type interpretation regardless of which cues occurs to the left. The early cues to sentence modality in Spanish may not hold as much weight as the final cue, but it could be the case that the cues are interpreted additively: the final cue, the terminal F0 movement, could simply act as *confirmatory*, rather than the one that leads the listener to perceive sentence type. If that is the case, we would expect accurate anticipatory behavior in response to the early cues.

## Prediction in a Second Language

If it is accurate that L1 Spain Spanish speakers may not recruit early intonational cues to predict sentence type [@roettger2021positional], do late sequential second language (L2) Spanish learners expend cognitive resources to make use of the same cues for the same purpose? Contrary to early claims [@gruter2014role], L2 speakers have been found to predict, leading to a growing flourish of research [see @gruter2021prediction], so it is not impossible that they make predictions based on this information. In fact, even L2 learners with very little experience in the L2 are capable of predicting [@koehne2015interplay]. But what determines if an L2 speaker acquires and takes advantage of early cues to predict?

There are few current L2 learning models that provide a framework for learning intonation. One available model is the L2 Intonation Learning theory [LILt; @mennen2015beyond], which predicts L2 learner outcomes by comparing the intonational systems of the two languages on four dimensions, predicated on L1-L2 transfer: the inventory and distribution of categorical phonological elements; the phonetic implementation of those elements; the functionality of the elements; and the frequency of use of each element. Unfortunately, there is only one cue that would traditionally be considered categorical in Spanish for sentence modality, and thus relevant to the model, that being the boundary tone [@prieto2010transcription]. Canonical yes-no questions are typically thought of as cued by a high boundary tone, but this does not actually seem to be the case: @geluykens1988myth found that it is more frequent to find low boundary tones with canonical yes-no questions in English. As such, the LILt model would actually predict some difficulty in acquiring a high boundary tone for Spanish yes-no questions by L1 English L2 Spanish learners.

It is not clear what predictions LILt might make for acquiring the earlier intonational cues in Spanish, as they are not considered categorical in nature. Furthermore, the intonational cues to sentence modality do not have clear correlates between English and Spanish, especially because English declaratives and canonical yes-no questions are primarily distinguished by syntactic and lexical differences. For example, while the first pitch peak in Spanish is different between declaratives and yes-no interrogatives, pitch peak height in prenuclear accents has been found to be correlated with emphasis in British [@ladd1997perception] and American [@chen2003reaction] English, not sentence type. Since there are no commonalities between Spanish and English yes-no questions, it may be the case that only negative transfer has the possibility of occurring in this case.

It is clear that L2 learners *can* predict in a qualitatively similar manner to L1 speakers, although typically with a delay, but it is unclear what determines their ability to do so. If @roettger2019evidential['s] computational model is to be adapted to an L2 context, we may wonder if L2 speakers with more opportunities to hear and utilize the cue-to-function mapping will show (faster) anticipatory behavior? @kaan2021prediction also point to this direction by suggesting that prediction in the L2 is modulated by utility (as opposed to e.g., proficiency). Generating predictions is dependent on reliable cues and correct predictions most of the time.

Two groups of L1 English L2 Spanish consecutive interpreters, one operating within an English-speaking legal system and the other within a Spanish-speaking one, may help to address this question. Consecutive court interpreters working within an English system are predicted to interpret many more questions from English to Spanish, whereas the reverse would be true for the Spanish legal system. Both groups represent high-proficiency, high language-use L2 learners who differ primarily in how often they must interpret Spanish yes-no questions into English.

## Research Questions

Prediction of sentence type in interpreters is reliant on utility. Court interpreters in Spain are more likely to interpret questions from Spanish to English, so they must predict whether an utterance is a declarative or interrogative more often.

# Method

## Participants

L1 Spanish monolinguals. L1 English L2 Spanish court interpreters in Spain. L1 English L2 Spanish court interpreters in Gibraltar.

## Experimental Task

Using the visual-world eye-tracking paradigm, participants were tested to determine if they were able to accurately determine whether a sentence was a declarative or interrogative before the final syllable.

### Critical Trials


### Auditory Stimuli


### Visual Stimuli


## Procedure

# Results

# Discussion

## Limitations and Future Directions

## Conclusion

# RANDOM SNIPPETS, DELETE ME LATER 

With specific regards to intonational cues, @foltz2021using in an eye-tracking study found that L1 German L2 English intermediate-to-advanced learners [B2 or above using CEFR levels; @coucilofeurope2001cefr] were able to predict a referent based on a contrastive pitch accent in their L1, but showed delayed processing for the same cue-to-function mapping in their L2. This is in contrast to @klassen2015second, who found that intermediate-to-advanced Spanish-English bilinguals *did* engage in predictive processing for a similar cue-to-function mapping between languages.

@marasco2020you Gating experiment a la Face 2007. L2 = native speaker for reaction times at gate 1. Three gates. The first right after first pitch peak. Statistics only completed for first date; third gate's RTs are reported, but statistics are not completed on it.

Importantly, they attribute these differing results to timing: where @klassen2015second separated two phrases of an instruction with 700 ms of silence, the target noun in @foltz2021using immediately followed the cue-bearing adjective. Thus, it may be expected that if given enough time (i.e., a longer sentence length), L2 Spanish speakers may integrate early intonational cues.

An open question is *which* information perceivers recruit to make predictions about *what* content. 

As such, although it is clear that L1 Spanish speakers *can* recruit early intonational cues to accurately predict sentence modality [@face2007role], it is yet to be seen if they *do* recruit the early cues during real-time sentence processing.

For example, @esteve2020empathy in an eye-tracking experiment found that L1 French speakers can recruit intonational information to accurately disambiguate cognates. @ito2008anticipatory investigated L1 English speakers' perception of the felicitous and infelicitous use of the L+H* pitch accent, associated with contrastive focus, in one of their three eye-tracking experiments reported. In experiment 2, they found that listeners had earlier target fixations when presented with the contrastive pitch accent and demonstrated a garden path effect when the contrastive pitch accent was used infelicitously. These studies indicate that intonational information *can* recruited during real-time sentence processing to predict upcoming information.

In an off-line gating experiment, @face2007role determined that L1 Spanish speakers are capable of recruiting early intonational 

but it remains unclear if speakers do recruit the relevant early intonational information during real-time sentence processing.

# References

<!-- References will auto-populate in the refs div below -->

::: {#refs}
:::

# This Section Is an Appendix {#apx-a}


# Another Appendix {#apx-b}